# Generated by Django 3.2 on 2021-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=100)),
                ('Availability', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('ReturnDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('GenreId', models.AutoField(primary_key=True, serialize=False)),
                ('GenreName', models.CharField(max_length=100)),
            ],
        ),
    ]
